In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
path = "/content/drive/MyDrive/praktikum_ml/praktikum07/data/"

In [10]:
import pandas as pd

df = pd.read_csv(path + "dataset_satelit.csv")

df

,No,Longitude,Lattitude,N,P,K,Ca,Mg,Fe,Mn,...,b1,Sigma_VV,Sigma_VH,plia,lia,iafe,gamma0_vv,gamma0_vh,beta0_vv,beta0_vh
0,1,103.036658,-0.604417,2.64,0.15,0.415,0.51,0.31,119.96,463.23,...,0.0433,0.18183,0.04461,35.74446,35.79744,35.41161,0.22331,0.05479,0.31325,0.07686
1,2,103.037201,-0.604689,2.75,0.17,0.568,0.76,0.58,102.63,493.81,...,0.0465,0.22079,0.04640,35.12096,35.14591,35.41510,0.27116,0.05699,0.38033,0.07993
2,3,103.036359,-0.603012,1.77,0.12,0.339,0.49,0.6,107.37,460.93,...,0.0417,0.18926,0.03992,35.07724,35.07730,35.41135,0.23242,0.04902,0.32604,0.06876
3,4,103.036950,-0.603219,2.30,0.15,0.460,0.74,0.67,96.02,338.17,...,0.0367,0.14769,0.03622,36.08078,36.08469,35.41583,0.18138,0.04448,0.25440,0.06238
4,5,103.036802,-0.601969,2.05,0.14,0.308,0.64,0.72,87.01,384.33,...,0.0361,0.18205,0.03797,32.68855,32.69293,35.41592,0.22359,0.04664,0.31359,0.06541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,590,103.605867,0.057633,2.49,0.16,0.347,0.78,0.86,63.38,269.95,...,0.2336,0.13050,0.09390,0.12700,0.09860,0.02600,0.00870,0.01690,0.00930,0.01630
590,591,103.606717,0.057100,2.74,0.15,0.466,0.73,0.5,51.04,683.42,...,0.2506,0.21280,0.15920,0.20060,0.14730,0.03870,0.01380,0.02290,0.01270,0.01640
591,592,103.606250,0.056767,2.63,0.15,0.422,0.82,0.59,82.57,396.18,...,0.3413,0.27730,0.17820,0.25790,0.18690,0.04620,0.01250,0.02250,0.01600,0.01930
592,593,103.606400,0.056517,2.75,0.17,0.502,0.69,0.53,102.07,246.35,...,0.3413,0.32740,0.28760,0.29970,0.22250,0.05290,0.01800,0.03350,0.01790,0.01930
593,594,103.606033,0.056317,2.71,0.15,0.419,0.78,0.46,90.60,371.46,...,0.3482,0.41280,0.36380,0.38660,0.28990,0.06830,0.02160,0.04460,0.02050,0.02220

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 34 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         594 non-null    int64
 1   Longitude  594 non-null    float64
 2   Lattitude  594 non-null    float64
 3   N          594 non-null    float64
 4   P          594 non-null    float64
 5   K          593 non-null    float64
 6   Ca         594 non-null    float64
 7   Mg         594 non-null    object
 8   Fe         594 non-null    float64
 9   Mn         594 non-null    float64
 10  Cu         594 non-null    float64
 11  Zn         594 non-null    float64
 12  B          594 non-null    float64
 13  b12        594 non-null    float64
 14  b11        594 non-null    float64
 15  b9         594 non-null    float64
 16  b8a        594 non-null    float64
 17  b8         594 non-null    float64
 18  b7         594 non-null    float64
 19  b6         594 non-null    float64
 20  b5         594 non-null    float64
 21  b4         594 non-null    float64
 22  b3         594 non-null    float64
 23  b2         594 non-null    float64
 24  b1         594 non-null    float64
 25  Sigma_VV   594 non-null    float64
 26  Sigma_VH   594 non-null    float64
 27  plia       594 non-null    float64
 28  lia        594 non-null    float64
 29  iafe       594 non-null    float64
 30  gamma0_vv  594 non-null    float64
 31  gamma0_vh  594 non-null    float64
 32  beta0_vv   594 non-null    float64
 33  beta0_vh   594 non-null    float64
dtypes: float64(32), int64(1), object(1)
memory usage: 157.9+ KB

In [13]:
df['K'] = df['K'].fillna(df['K'].median())
df['Mg'] = pd.to_numeric(df['Mg'], errors='coerce')
df['Mg'] = df['Mg'].fillna(df['Mg'].median())

In [15]:
from sklearn.model_selection import train_test_split

X = df[['b12','gamma0_vv']]
y = df[['Ca']]

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)


print(f"Jumlah data training: {len(X_train)}")
print(f"Jumlah data testing: {len(X_test)}")

Jumlah data training: 475
Jumlah data testing: 119

In [17]:
import statsmodels.api as sm

X_train_const = sm.add_constant(X_train)
X_test_const = sm.add_constant(X_test)

model = sm.OLS(y_train, X_train_const).fit()


print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Ca   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     2.886
Date:                Sun, 09 Nov 2025   Prob (F-statistic):             0.0568
Time:                        13:09:03   Log-Likelihood:                -210.47
No. Observations:                 475   AIC:                             426.9
Df Residuals:                     472   BIC:                             439.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7316      0.061     12.073      0.000       0.613       0.851
b12           -0.3932      0.308     -1.277      0.202      -0.998       0.212
gamma0_vv     -0.3991      0.174     -2.299      0.022      -0.740      -0.058
==============================================================================
Omnibus:                      109.929   Durbin-Watson:                   2.175
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              255.577
Skew:                           1.183   Prob(JB):                     3.18e-56
Kurtosis:                       5.704   Cond. No.                         18.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [32]:
import numpy as np
import pandas as pd

X_test_const = sm.add_constant(X_test)

y_pred_test = model.predict(X_test_const)

hasil = pd.DataFrame({
    "b12": X_test["b12"].to_numpy(),
    "gamma0_vv": X_test["gamma0_vv"].to_numpy(),
    "Ca Aktual": y_test['Ca'].to_numpy(),
    "Ca Prediksi": y_pred_test
})

hasil["Selisih error"] = hasil["Ca Prediksi"] - hasil["Ca Aktual"]

denom = hasil["Ca Aktual"].replace(0, np.nan)
hasil["Akurasi (%)"] = (1 - (hasil["Selisih error"].abs() / denom)).clip(lower=0, upper=1) * 100

print("=== HASIL PREDIKSI ===")
hasil

=== HASIL PREDIKSI ===

         b12  gamma0_vv  Ca Aktual  Ca Prediksi  Selisih error  Akurasi (%)
30   0.09920    0.23984       0.22     0.596909       0.376909     0.000000
299  0.10250    0.28774       0.86     0.576493      -0.283507    67.034064
177  0.22360    0.25786       0.61     0.540807      -0.069193    88.656933
204  0.23160    0.22463       0.27     0.550926       0.280926     0.000000
354  0.09230    0.27901       1.01     0.583988      -0.426012    57.820569
..       ...        ...        ...          ...            ...          ...
580  0.12047    0.02030       0.56     0.676175       0.116175    79.254470
228  0.13130    0.33728       0.25     0.545396       0.295396     0.000000
84   0.09330    0.18222       0.63     0.622228      -0.007772    98.766312
140  0.11070    0.22438       1.03     0.598559      -0.431441    58.112504
394  0.03910    0.19288       0.97     0.639282      -0.330718    65.905396

[119 rows x 6 columns]